name: "Bug report / バグ報告"
description: "Report unexpected behavior / 想定外の挙動を報告"
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting.
        報告ありがとうございます。
        A short report is fine.
        短い報告でもOKです。

  - type: textarea
    id: problem
    attributes:
      label: "What happened? / 何が起きたか"
      placeholder: "Example: App crashed after pressing Enter / 例: Enter後にクラッシュ"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps (optional) / 再現手順（任意）"
      placeholder: |
        1. ...
        2. ...

  - type: input
    id: environment
    attributes:
      label: "Environment (optional) / 環境（任意）"
      placeholder: "macOS + Tauri dev / Browser + npm run dev"

  - type: textarea
    id: logs
    attributes:
      label: "Logs / screenshots (optional) / ログ・スクリーンショット（任意）"
