name: "Bug report / バグ報告"
description: "Report unexpected behavior / 想定外の挙動を報告"
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting.
        報告ありがとうございます。

  - type: textarea
    id: summary
    attributes:
      label: "Summary / 概要"
      description: "What happened? / 何が起きましたか？"
      placeholder: "A short description of the issue / 問題の要約"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce / 再現手順"
      description: "Please include exact steps. / できるだけ具体的に記載してください。"
      placeholder: |
        1. Go to ...
        2. Press ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior / 期待する動作"
      placeholder: "What did you expect to happen? / 本来どうなるべきでしたか？"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior / 実際の動作"
      placeholder: "What actually happened? / 実際に何が起きましたか？"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "Platform / 実行環境"
      options:
        - macOS (Tauri)
        - Windows (Tauri)
        - Linux (Tauri)
        - Browser (npm run dev)
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: "App/Commit version / アプリ・コミット情報"
      description: "Commit SHA or app version if known / 分かればコミットSHAやバージョン"
      placeholder: "e.g. 1a2b3c4"

  - type: textarea
    id: logs
    attributes:
      label: "Logs or screenshots / ログ・スクリーンショット"
      description: "Optional but helpful / 任意ですがあると助かります"

  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist / 確認事項"
      options:
        - label: "I searched existing issues. / 既存 Issue を確認しました"
          required: true
        - label: "I can reproduce this with current main branch. / 最新 main でも再現します"
          required: false
