name: "Feature request / 機能提案"
description: "Suggest an improvement / 機能改善の提案"
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for the idea.
        提案ありがとうございます。
        A rough idea is welcome.
        ラフなアイデアでも歓迎です。

  - type: textarea
    id: idea
    attributes:
      label: "Idea / アイデア"
      placeholder: "What would you like to add or improve? / 追加・改善したいこと"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Why (optional) / 期待効果（任意）"
      placeholder: "Why is this useful? / なぜ便利か"

  - type: textarea
    id: context
    attributes:
      label: "Notes (optional) / 補足（任意）"
      placeholder: "Examples, mockups, references, etc. / 例、モック、参考資料など"
