name: "Question / 質問"
description: "Ask a usage or design question / 使い方や設計について質問"
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Simple questions are welcome.
        気軽な質問でも歓迎です。

  - type: textarea
    id: question
    attributes:
      label: "Your question / 質問内容"
      placeholder: "What do you want to know? / 何を知りたいか"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context (optional) / 背景（任意）"
      placeholder: "What you tried, environment, screenshots, etc. / 試したこと、環境、スクショなど"
